# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages:
    - build
    - compile

cache:
    paths:
        - node_modules/
        # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
        - .cache/
        - public/

pages:
    image: node:latest
    stage: build
    variables:
        FF_USE_FASTZIP: "true"
        ARTIFACT_COMPRESSION_LEVEL: "fastest"

    script:
        - npm install
        - ./node_modules/.bin/gatsby build --prefix-paths
    artifacts:
        paths:
            - public
    only:
        - main
